// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:26be3a34-7bd9-4987-86c6-52a5cf04a638",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_UdLm61VrT",
    "aws_user_pools_web_client_id": "6535ia8ovghl03l9ur6fs3ik01",
    "oauth": {
        "domain": "insight1017-insight.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/profile/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
